spring:
  application:
    name: auth-service
  data:
    mongodb:
      port: 27017
      database: mongo_auth

server:
  port: 8881


security:
  basic:
    enable: false
  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey