version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongo_auth"
    environment:
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - /Users/mustafa.kurt/mkurt/instamic-persistent/mongodb:/data/db