spring:
  application:
    name: media-service
  data:
    mongodb:
      port: 27017
      database: mongo_media

server:
  port: 8882

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

file:
  upload-dir: /Users/mustafa.kurt/mkurt/instamic-persistent/images
  path:
    prefix: /images